### ISSUE TITLE
Run time longer than expected

### ISSUE THREAD

**Issue by bmansfeld** [daihang16/nubeamdedup#1]
Hi, 
Thanks for developing the tool! and congrats on the publication in _Bioinformatics_!
I recently ran numbeam-dedup on a 500M PE 151bp data set using the following command:

`~/nubeamdedup-master/Linux/nubeam-dedup -i1 sampleName_R1.fastq.gz -i2 sampleName_R2.fastq.gz -s 1 -r 0 -z 6`

I unfortunately did not run a usage statistics command but the approximate run time was 13-15 hrs and at ~7hrs in I did check my usage and was using about 19GB of RAM. Extrapolating on that I would have to guess that the total RAM would be about 40+ GB for this set. 

This is slower than the 3,000,000,000x2 read example from the paper even with `-s`. 

For future use I wonder if I was running the command wrong? Or if there is a good way to run this faster? Perhaps it was the `-z` that increased the run time?

Please advise.
Thanks again for the tool, I have already recommended to a colleague! 

Ben

**Comment by daihang16** [comment]
Dear Dr. Mansfeld,

Thank you for your interest in our tool. Hope you would find it useful for your research. 

First, I agree with you that the expected peak RAM would be about 40Gb. From Table 1 in the paper, 700Mx2 reads took 57Gb, 3100Mx2 reads took 280Gb; a linear model suggests that 500Mx2 reads would take about 38Gb. 

Second, the command you ran is totally correct. But I agree with you that `-z 6` might significantly increase the running time. From Figures 1, 2 and 7 in [this post](https://clearlinux.org/news-blogs/linux-os-data-compression-options-comparing-behavior), `-z 6` would increase the amount of time by a factor of 2.5-3 compared with `-z 1` (with a limited gain regarding to compression ratio); and `-z 1` would increase the amount of time by a factor of 2.5 compared with `-z 0`, which is the default setting of `nubeam-dedup`. 

So my current suggestion is either use a smaller compression level or remove the `-z` tag from the command. For the latter choice, if compression was required, you could use [pigz](https://zlib.net/pigz/) after `nubeam-dedup` finishes---this can significantly accelerate the compression.

Hope it helps. Please kindly let me know if this works. 

Hang

**Comment by bmansfeld** [comment]
Hey Hang,
Thanks for the quick reply and the suggestions.
Next time around I will try to run without compression and see if that substantially improves run time. 
Thanks again,
Ben
