### ISSUE TITLE
请问没有root权限如何编译安装该软件

### ISSUE THREAD

**Issue by SeqCrafter** [daihang16/nubeamdedup#2]
是不是应该修改make文件，可是该如何修改呢

**Comment by SeqCrafter** [comment]
Since I don't have root access, many dependencies are not in usr/ below, how do I modify the make file in this case?

**Comment by daihang16** [comment]
My guess is that root access is not needed, as I do not have root access on the computer I am using either.  Would you please let me know the error messages? Thank you.

**Comment by daihang16** [comment]
Also, if you use Linux system, please try if the pre-compiled binary file `nubeam-dedup` works on toy data.

**Comment by SeqCrafter** [comment]
I think the STATICLIBS in Makefile should be modified because this is the installation path of zlib, but if the user does not have root access, the installation of the package needs to be redirected to a different path, so it needs to be modified itself.

**Comment by daihang16** [comment]
Thank you for raising the issue. I will include the zlib into the installation folder and modify the Makefile for the convenience of users.  I will let you know when it is done. Meanwhile, please try if the pre-compiled binary file `nubeam-dedup` works on toy data. Thank you.

**Comment by daihang16** [comment]
@panxiaoguang I have included zlib in this commit (https://github.com/daihang16/nubeamdedup/commit/4f1ceca1ad02af94332975166b3c9c59a98d0465)
Please checkout the latest code on master branch.
