### ISSUE TITLE
exitcode 1 without any error message

### ISSUE THREAD

**Issue by alxsimon** [daihang16/nubeamdedup#3]
Hi,
when using nubeam-dedup as such:
`nubeam-dedup -i1 {fq1} -i2 {fq2} -o1 {out1} -o2 {out2}`
the process works fine and output large fastq files as expected.
It also writes the output message as expected.

However it exits with an exitcode of 1, which messes up with the snakemake workflow.

I don't know if this exitcode is really an error (as no error message is displayed) or just an exitcode mistake.
Thanks

**Comment by daihang16** [comment]
Thank you for raising the issue Dr. Simon. I will check and let you know.

**Comment by daihang16** [comment]
Thank you for raising the issue Dr. Simon. I have no experience in `snakemake`, but I find [this](https://snakemake.readthedocs.io/en/stable/project_info/faq.html#i-don-t-want-snakemake-to-detect-an-error-if-my-shell-command-exits-with-an-exitcode-1-what-can-i-do), perhaps worth a try as a temporary _ad hoc_ measure. Please let me know if it works. Meanwhile, I will check the exitcode issue in `nubeam-dedup` script and let you know later.

**Comment by alxsimon** [comment]
Thank you, this is indeed what I have been doing so far and it works fine. I am more worried if their is an undetected problem with the final fastq files.

**Comment by alxsimon** [comment]
Just to complete the investigation.
I ran the following script `test_nubeam.sh` inside a singularity image where nubeam-dedup is installed
```
#! /usr/bin/env bash

set +e
nubeam-dedup -i1 /opt/nubeamdedup/toydata/1.fq.gz -i2 /opt/nubeamdedup/toydata/2.fq.gz
exitcode=$?
echo "exitcode: ${exitcode}"
wc -l *.fastq
```

`singularity exec assembly_10x/containers/assembly_tools.sif bash test_nubeam.sh`

which gives me
```
Output unique read pairs read 1 to /data/ref_genomes/1.uniq.fastq 
Output unique read pairs read 2 to /data/ref_genomes/2.uniq.fastq 
exitcode: 1    
  276884 1.uniq.fastq 
  276884 2.uniq.fastq 
  553768 total
```

So even with the test data there is an exicode 1.

**Comment by daihang16** [comment]
Thank you for the information. This is caused by the inappropriate exit code I specified in the script. There is no problem with the final fastq files. I am sorry about the problem and will fix it and let you know.

**Comment by daihang16** [comment]
Dear Dr. Simon,

Thank you for raising the issue, which has been fixed as below. Please let me know if it works in `snakemake`. Thank you.

```console
foo@bar:~/nubeamdedup/Linux$ ./nubeam-dedup -i1 ../toydata/1.fq.gz -i2 ../toydata/2.fq.gz
Output unique read pairs read 1 to ~/nubeamdedup/Linux/1.uniq.fastq
Output unique read pairs read 2 to ~/nubeamdedup/Linux/2.uniq.fastq
foo@bar:~/nubeamdedup/Linux$ echo $?
0
```

**Comment by alxsimon** [comment]
Great, I haven't tested it yet but it should work fine in snakemake.
Thank you very much for your quick fix.
